sudo: required
services:
  - docker

before_install:
  - docker build -t jrcetelem/docker-kubernetes-udemy-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jrcetelem/docker-kubernetes-udemy-react npm run test